# Starter pipeline
# Pull from Repo
# Import Project into Docekr SOAtest CLI container and Run
# Azure YAML docs:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Build Stage 
# Deploy Stage
# Test Stage
- script: |
    
    # Set Up and write .properties file
    echo  -e "\n~~~\nSetting up and creating soatestcli.properties file.\n"
    echo $"
    license.network.auth.enabled=true  
    license.network.password=$(license.server.password)
    license.network.url=$(license.server.url)
    license.network.use.specified.server=true
    license.network.user=admin
    soatest.license.network.edition=automation_edition
    soatest.license.use_network=true
    virtualize.license.network.edition=performance_server_edition
    virtualize.license.use_network=true" >> soatestcli.properties
    
    # Debugging
    echo -e "\nDebug -- Verify workspace contents.\n"
    ls -R
    echo -e "\nDebug -- Verify soatestcli.properties file contents."
    cat soatestcli.properties

    # Run Docker container with mount and run tests
    echo -e "\n~~~\nRun SOAtestCLI Docker container & mount ./$(pwd) volume.\n"
    
    docker --version

    docker run -i \
    -u 0:0 \
    -e ACCEPT_EULA=true \
    -v "$(pwd):$(pwd)" \
    parasoft/soavirt /bin/bash -c " \
    cat soatestcli.properties; \
    soatestcli \
    -settings soatestcli.properties \
    -import $(pwd); \
    soatestcli \
    -resource /$() \
    -config 'user://Example Configuration' \
    -settings /$(pwd)/soatestcli.properties \
    -report /$(pwd)"

    echo -e "\nDebug -- Verify ./$(pwd) contents\n"
    ls -R $(pwd)/$(pwd)
  displayName: Run Tests
  env:
    pwd: $(Build.Repository.LocalPath)
  
# Publish Test Results
- task: PublishParasoftTestResults@1
  
  displayName: Publish SOAtest Test Results
  inputs:
    testRunner: 'SOAtest9x'
    testResultsFiles: '$(Build.Repository.LocalPath)/$(pwd)/rep*.xml'
